###간단한 DF

In [2]:
import pandas as pd
import numpy

df1 = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["A", "B", "C", "D"]
})

df2 = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 1, 2, 5],
    "amount": [30000, 12000, 45000, 9999]
})

df1, df2

(   customer_id name
 0            1    A
 1            2    B
 2            3    C
 3            4    D,
    order_id  customer_id  amount
 0       101            1   30000
 1       102            1   12000
 2       103            2   45000
 3       104            5    9999)

###INNER JOIN : 양쪽에 모두 있는 행만 합치기

In [3]:
inner = pd.merge(df1, df2, on="customer_id", how="inner")
inner

   customer_id name  order_id  amount
0            1    A       101   30000
1            1    A       102   12000
2            2    B       103   45000

###LEFT JOIN : 왼쪽 전부 살리기

In [4]:
left = pd.merge(df1, df2, on="customer_id", how="left")
left

   customer_id name  order_id   amount
0            1    A     101.0  30000.0
1            1    A     102.0  12000.0
2            2    B     103.0  45000.0
3            3    C       NaN      NaN
4            4    D       NaN      NaN

In [5]:
left_only = left[left["order_id"].isnull()]
left_only

   customer_id name  order_id  amount
3            3    C       NaN     NaN
4            4    D       NaN     NaN

###RIGHT JOIN : 오른쪽 전부 살리기

In [6]:
right = pd.merge(df1, df2, on="customer_id", how="right")
right

   customer_id name  order_id  amount
0            1    A       101   30000
1            1    A       102   12000
2            2    B       103   45000
3            5  NaN       104    9999

In [7]:
right_only = right[right["name"].isnull()]
right_only

   customer_id name  order_id  amount
3            5  NaN       104    9999

###FULL OUTER JOIN : 양쪽 모든 행 합치기

In [8]:
outer = pd.merge(df1, df2, on="customer_id", how="outer")
outer

   customer_id name  order_id   amount
0            1    A     101.0  30000.0
1            1    A     102.0  12000.0
2            2    B     103.0  45000.0
3            3    C       NaN      NaN
4            4    D       NaN      NaN
5            5  NaN     104.0   9999.0

###CONCAT

In [9]:
concat = pd.concat([df1, df2])
concat

   customer_id name  order_id   amount
0            1    A       NaN      NaN
1            2    B       NaN      NaN
2            3    C       NaN      NaN
3            4    D       NaN      NaN
0            1  NaN     101.0  30000.0
1            1  NaN     102.0  12000.0
2            2  NaN     103.0  45000.0
3            5  NaN     104.0   9999.0

In [10]:
concat = pd.concat([df1, df2], axis=1)
concat

   customer_id name  order_id  customer_id  amount
0            1    A       101            1   30000
1            2    B       102            1   12000
2            3    C       103            2   45000
3            4    D       104            5    9999

###Olist data join

In [11]:
import pandas as pd

#파일 불러오기
customers = pd.read_csv("olist_customers_dataset.csv")
geolocation = pd.read_csv("olist_geolocation_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
order_payments = pd.read_csv("olist_order_payments_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")
orders = pd.read_csv("olist_orders_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
product_category = pd.read_csv("product_category_name_translation.csv")

#조인하기
merged_df = pd.merge(orders, order_items, on="order_id", how="outer")
merged_df = pd.merge(merged_df, order_payments, on="order_id", how="outer")
merged_df = pd.merge(merged_df, order_reviews, on="order_id", how="outer")
merged_df = pd.merge(merged_df, products, on="product_id", how="outer")
merged_df = pd.merge(merged_df, customers, on="customer_id", how="outer")
merged_df = pd.merge(merged_df, sellers, on="seller_id", how="outer")
display(merged_df)
print(merged_df.columns)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state
0,d455a8cb295653b55abda06d434ab492,944b72539d7e1f7f7fc6e46639ef1fe3,delivered,2017-09-26 22:17:05,2017-09-27 22:24:16,2017-09-29 15:53:03,2017-10-07 16:12:47,2017-10-30 00:00:00,1.0,a2ff5a97bf95719e38ea2e3b4105bce8,...,40.0,43.0,36.0,3c7e305796add66698959fc7ad176f6b,87502,umuarama,PR,9080.0,santo andre,SP
1,7f39ba4c9052be115350065d07583cac,d7fc82cbeafea77bd0a8fbbf6296e387,delivered,2017-10-18 08:16:34,2017-10-18 23:56:20,2017-10-20 14:29:01,2017-10-27 16:46:05,2017-11-09 00:00:00,1.0,a2ff5a97bf95719e38ea2e3b4105bce8,...,40.0,43.0,36.0,9de5797cddb92598755a0f76383ddbbb,35490,entre rios de minas,MG,9080.0,santo andre,SP
2,9dc8d1a6f16f1b89874c29c9d8d30447,d9442164acf4b03109425633efaa0cfc,delivered,2017-10-12 13:33:22,2017-10-12 13:49:22,2017-10-17 15:42:42,2017-10-24 20:17:44,2017-11-06 00:00:00,1.0,a2ff5a97bf95719e38ea2e3b4105bce8,...,40.0,43.0,36.0,9915eb9f74b6c11aaf04833f65b00e93,38600,paracatu,MG,9080.0,santo andre,SP
3,0f548bd29148ebc519d6495e37a284e1,015faf9ec36eccd957c0f2782aab09a4,delivered,2017-09-03 08:06:30,2017-09-03 08:25:50,2017-09-04 22:03:06,2017-09-08 16:26:55,2017-09-27 00:00:00,1.0,08574b074924071f4e201e151b152b4e,...,42.0,12.0,39.0,dce323533e45e74d215e0fe7fb114118,24710,sao goncalo,RJ,29156.0,cariacica,ES
4,0f548bd29148ebc519d6495e37a284e1,015faf9ec36eccd957c0f2782aab09a4,delivered,2017-09-03 08:06:30,2017-09-03 08:25:50,2017-09-04 22:03:06,2017-09-08 16:26:55,2017-09-27 00:00:00,2.0,08574b074924071f4e201e151b152b4e,...,42.0,12.0,39.0,dce323533e45e74d215e0fe7fb114118,24710,sao goncalo,RJ,29156.0,cariacica,ES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119138,87ae60ef8b08ae0e5f903cacb53a6904,fea4d57ed3a45455f89c25ef3dae8ee8,canceled,2018-09-11 16:45:54,NaN,NaN,NaN,2018-09-26 00:00:00,NaN,NaN,...,NaN,NaN,NaN,09687a7b7431a93b5c53b50ba779bf94,12010,taubate,SP,NaN,NaN,NaN
119139,d69fcef5a5fe3a3db60ea65c6ee499cc,ff0340330283c0d05ea7281e67fa2e76,unavailable,2017-12-02 10:11:44,2017-12-02 10:30:31,NaN,NaN,2018-01-08 00:00:00,NaN,NaN,...,NaN,NaN,NaN,dc80a79483121fee90b0d2f53d1054f5,57046,maceio,AL,NaN,NaN,NaN
119140,f86d7bc39aab05299691322044b63bb2,ff31bee1ba4bba00cc14b1b91c8d28f3,canceled,2018-08-13 18:43:06,NaN,NaN,NaN,2018-09-25 00:00:00,NaN,NaN,...,NaN,NaN,NaN,a0931a30dcf7e2106f0939b799c54321,76804,porto velho,RO,NaN,NaN,NaN
119141,74f833bf7c70ce8c3f820f725c213e1c,fffc22669ca576ae3f654ea64c8f36be,unavailable,2017-06-30 11:21:11,2017-06-30 11:30:20,NaN,NaN,2017-08-01 00:00:00,NaN,NaN,...,NaN,NaN,NaN,0f21adf44f13a61282678a89f6433c10,40255,salvador,BA,NaN,NaN,NaN
119142,2e935fa1d39497aa0ec3f1107fbfb5b8,ffffe8b65bbe3087b653a978c870db99,unavailable,2017-09-29 14:07:03,2017-10-03 06:34:13,NaN,NaN,2017-10-24 00:00:00,NaN,NaN,...,NaN,NaN,NaN,736e6bfa0510aa5b878881a226a5fd89,6172,osasco,SP,NaN,NaN,NaN

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'review_id', 'review_score',
       'review_comment_title', 'review_comment_message',
       'review_creation_date', 'review_answer_timestamp',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'seller_zip_code_prefix', 'seller_city',
       'seller_state'],
      dtype='str')