###간단한 DF

In [ ]:
import pandas as pd
import numpy

customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["A", "B", "C", "D"]
})

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 1, 2, 5],
    "amount": [30000, 12000, 45000, 9999]
})

customers, orders

(   customer_id name
 0            1    A
 1            2    B
 2            3    C
 3            4    D,
    order_id  customer_id  amount
 0       101            1   30000
 1       102            1   12000
 2       103            2   45000
 3       104            5    9999)

###INNER JOIN : 양쪽에 모두 있는 행만 합치기

In [ ]:
inner = pd.merge( customers,  orders, on="customer_id", how="inner")
inner

   customer_id name  order_id  amount
0            1    A       101   30000
1            1    A       102   12000
2            2    B       103   45000

###LEFT JOIN : 왼쪽 전부 살리기

In [ ]:
left = pd.merge(customers,orders, on="customer_id", how="left")
left

   customer_id name  order_id   amount
0            1    A     101.0  30000.0
1            1    A     102.0  12000.0
2            2    B     103.0  45000.0
3            3    C       NaN      NaN
4            4    D       NaN      NaN

In [ ]:
left_only = left[left["order_id"].isnull()]
left_only

   customer_id name  order_id  amount
3            3    C       NaN     NaN
4            4    D       NaN     NaN

###RIGHT JOIN : 오른쪽 전부 살리기

In [ ]:
right = pd.merge(customers, orders, on="customer_id", how="right")
right

   customer_id name  order_id  amount
0            1    A       101   30000
1            1    A       102   12000
2            2    B       103   45000
3            5  NaN       104    9999

In [ ]:
right_only = right[right["name"].isnull()]
right_only

   customer_id name  order_id  amount
3            5  NaN       104    9999

###FULL OUTER JOIN : 양쪽 모든 행 합치기

In [ ]:
outer = pd.merge(customers, orders, on="customer_id", how="outer",indicator=True)
outer

   customer_id name  order_id   amount      _merge
0            1    A     101.0  30000.0        both
1            1    A     102.0  12000.0        both
2            2    B     103.0  45000.0        both
3            3    C       NaN      NaN   left_only
4            4    D       NaN      NaN   left_only
5            5  NaN     104.0   9999.0  right_only

###CONCAT

In [ ]:
concat = pd.concat([customers,orders ])
concat

   customer_id name  order_id   amount
0            1    A       NaN      NaN
1            2    B       NaN      NaN
2            3    C       NaN      NaN
3            4    D       NaN      NaN
0            1  NaN     101.0  30000.0
1            1  NaN     102.0  12000.0
2            2  NaN     103.0  45000.0
3            5  NaN     104.0   9999.0

In [ ]:
concat = pd.concat([customers,orders ], axis=1)
concat

   customer_id name  order_id  customer_id  amount
0            1    A       101            1   30000
1            2    B       102            1   12000
2            3    C       103            2   45000
3            4    D       104            5    9999

###Olist data join

In [ ]:
import pandas as pd

#파일 불러오기
customers =
geolocation =
order_items =
order_payments =
order_reviews =
orders =
products =
sellers =
product_category =

#조인하기


display(merged_df)
print(merged_df.columns)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,belo horizonte,SP,perfumery
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,guariba,SP,auto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119138,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,da62f9e57a76d978d02ab5362c509660,11722,...,828.0,4.0,4950.0,40.0,10.0,40.0,17602.0,tupa,SP,baby
119139,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,737520a9aad80b3fbbdad19b66b37b30,45920,...,500.0,2.0,13300.0,32.0,90.0,22.0,8290.0,sao paulo,SP,home_appliances_2
119140,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,28685,...,1893.0,1.0,6550.0,20.0,20.0,20.0,37175.0,ilicinea,MG,computers_accessories
119141,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,28685,...,1893.0,1.0,6550.0,20.0,20.0,20.0,37175.0,ilicinea,MG,computers_accessories
119142,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,60350aa974b26ff12caad89e55993bd6,83750,...,569.0,1.0,150.0,16.0,7.0,15.0,14407.0,franca,SP,health_beauty

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value', 'review_id',
       'review_score', 'review_comment_title', 'review_comment_message',
       'review_creation_date', 'review_answer_timestamp',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'product_category_name_english'],
      dtype='object')