###간단한 DF

In [1]:
import pandas as pd
import numpy

customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["A", "B", "C", "D"]
})

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 1, 2, 5],
    "amount": [30000, 12000, 45000, 9999]
})

customers, orders

(   customer_id name
 0            1    A
 1            2    B
 2            3    C
 3            4    D,
    order_id  customer_id  amount
 0       101            1   30000
 1       102            1   12000
 2       103            2   45000
 3       104            5    9999)

###INNER JOIN : 양쪽에 모두 있는 행만 합치기

In [2]:
inner = pd.merge(customers, orders, on = "customer_id", how = "inner")
inner

   customer_id name  order_id  amount
0            1    A       101   30000
1            1    A       102   12000
2            2    B       103   45000

###LEFT JOIN : 왼쪽 전부 살리기

In [3]:
left = pd.merge(customers, orders, on = 'customer_id', how = 'left')
left

   customer_id name  order_id   amount
0            1    A     101.0  30000.0
1            1    A     102.0  12000.0
2            2    B     103.0  45000.0
3            3    C       NaN      NaN
4            4    D       NaN      NaN

In [ ]:
left_only = left[left["order_id"].isnull()]
left_only

   customer_id name  order_id  amount
3            3    C       NaN     NaN
4            4    D       NaN     NaN

###RIGHT JOIN : 오른쪽 전부 살리기

In [ ]:
right = pd.merge(customers, orders, on="customer_id", how="right")
right

In [ ]:
right_only = right[right["name"].isnull()]
right_only

   customer_id name  order_id  amount
3            5  NaN       104    9999

###FULL OUTER JOIN : 양쪽 모든 행 합치기

In [4]:
outer = pd.merge(customers, orders, on = "customer_id", how = "outer", indicator = True)
outer

   customer_id name  order_id   amount      _merge
0            1    A     101.0  30000.0        both
1            1    A     102.0  12000.0        both
2            2    B     103.0  45000.0        both
3            3    C       NaN      NaN   left_only
4            4    D       NaN      NaN   left_only
5            5  NaN     104.0   9999.0  right_only

###CONCAT

In [6]:
concat = pd.concat([customers, orders])
concat

   customer_id name  order_id   amount
0            1    A       NaN      NaN
1            2    B       NaN      NaN
2            3    C       NaN      NaN
3            4    D       NaN      NaN
0            1  NaN     101.0  30000.0
1            1  NaN     102.0  12000.0
2            2  NaN     103.0  45000.0
3            5  NaN     104.0   9999.0

In [7]:
concat = pd.concat([customers, orders], axis = 1)
concat

   customer_id name  order_id  customer_id  amount
0            1    A       101            1   30000
1            2    B       102            1   12000
2            3    C       103            2   45000
3            4    D       104            5    9999

###Olist data join

In [ ]:
import pandas as pd

#파일 불러오기
customers = pd.read_csv("olist_customers_dataset.csv")
geolocation = pd.read_csv("olist_geolocation_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
order_payments = pd.read_csv("olist_order_payments_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")
orders = pd.read_csv("olist_orders_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
product_category = pd.read_csv("product_category_name_translation.csv")

#조인하기
merged_df = orders.merge(customers, on="customer_id", how="left")
merged_df = merged_df.merge(order_items, on="order_id", how="left")
merged_df = merged_df.merge(order_payments, on="order_id", how="left")
merged_df = merged_df.merge(order_reviews, on="order_id", how="left")
merged_df = merged_df.merge(products, on="product_id", how="left")
merged_df = merged_df.merge(sellers, on="seller_id", how="left")
merged_df = merged_df.merge(product_category, on="product_category_name", how="left")

display(merged_df)
print(merged_df.columns)