###간단한 DF

In [8]:
import pandas as pd
import numpy

customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["A", "B", "C", "D"]
})

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 1, 2, 5],
    "amount": [30000, 12000, 45000, 9999]
})

customers, orders

(   customer_id name
 0            1    A
 1            2    B
 2            3    C
 3            4    D,
    order_id  customer_id  amount
 0       101            1   30000
 1       102            1   12000
 2       103            2   45000
 3       104            5    9999)

###INNER JOIN : 양쪽에 모두 있는 행만 합치기

In [9]:
inner = pd.merge(customers, orders, on="customer_id", how="inner")
inner

   customer_id name  order_id  amount
0            1    A       101   30000
1            1    A       102   12000
2            2    B       103   45000

###LEFT JOIN : 왼쪽 전부 살리기

In [12]:
left = pd.merge(customers, orders, on="customer_id", how="left")
left

   customer_id name  order_id   amount
0            1    A     101.0  30000.0
1            1    A     102.0  12000.0
2            2    B     103.0  45000.0
3            3    C       NaN      NaN
4            4    D       NaN      NaN

In [13]:
left_only = left[left["order_id"].isnull()]
left_only

   customer_id name  order_id  amount
3            3    C       NaN     NaN
4            4    D       NaN     NaN

###RIGHT JOIN : 오른쪽 전부 살리기

In [15]:
right = pd.merge(customers, orders, on="customer_id", how="right")
right

   customer_id name  order_id  amount
0            1    A       101   30000
1            1    A       102   12000
2            2    B       103   45000
3            5  NaN       104    9999

In [16]:
right_only = right[right["name"].isnull()]
right_only

   customer_id name  order_id  amount
3            5  NaN       104    9999

###FULL OUTER JOIN : 양쪽 모든 행 합치기

In [18]:
outer = pd.merge(customers, orders, on="customer_id", how="outer")
outer

   customer_id name  order_id   amount
0            1    A     101.0  30000.0
1            1    A     102.0  12000.0
2            2    B     103.0  45000.0
3            3    C       NaN      NaN
4            4    D       NaN      NaN
5            5  NaN     104.0   9999.0

###CONCAT

In [21]:
concat = pd.concat([customers, orders])
concat

   customer_id name  order_id   amount
0            1    A       NaN      NaN
1            2    B       NaN      NaN
2            3    C       NaN      NaN
3            4    D       NaN      NaN
0            1  NaN     101.0  30000.0
1            1  NaN     102.0  12000.0
2            2  NaN     103.0  45000.0
3            5  NaN     104.0   9999.0

In [22]:
concat = pd.concat([customers, orders], axis=1)
concat

   customer_id name  order_id  customer_id  amount
0            1    A       101            1   30000
1            2    B       102            1   12000
2            3    C       103            2   45000
3            4    D       104            5    9999

###Olist data join